/* Database schema to keep the structure of entire database. */

CREATE TABLE patients (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100),
    date_of_birth DATE,
    PRIMARY KEY(id)
);

CREATE TABLE medical_histories (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    admitted_at TIMESTAMP,
    patient_id INT,
    status VARCHAR(100),
    PRIMARY KEY(id),
    FOREIGN KEY (patient_id) REFERENCES patients(id) ON UPDATE CASCADE ON DELETE CASCADE,
);

CREATE TABLE invoices (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    total_amount DECIMAL,
    generated_at TIMESTAMP,
    payed_at TIMESTAMP,
    medical_history_id INT,
    PRIMARY KEY(id),
    FOREIGN KEY (medical_history_id) REFERENCES medical_histories(id) ON UPDATE CASCADE ON DELETE CASCADE,
);
